package com.partxis.clasificacion.ui

object Strings {
    fun get(key: String, language: String): String {
        val translations = translationsMap[language] ?: translationsMap["eu"]!!
        return translations[key] ?: key
    }

    private val translationsMap = mapOf(
        "eu" to mapOf(
            "app_name" to "Partxis",
            "no_clasificaciones" to "Ez dago sailkapenik",
            "toca_para_crear" to "Sakatu + sortzeko",
            "nueva_clasificacion" to "Sailkapen berria",
            "nombre" to "Izena",
            "crear" to "Sortu",
            "cancelar" to "Utzi",
            "eliminar" to "Ezabatu",
            "eliminar_clasificacion" to "Sailkapena ezabatu",
            "confirmar_eliminar" to "Ziur zaude? Datu guztiak ezabatuko dira.",
            "creada" to "Sortuta",
            "partidas" to "Partidak",
            "ranking" to "Sailkapena",
            "configuracion" to "Konfigurazioa",
            "nueva_partida" to "Partida berria",
            "sin_partidas" to "Partida gabe",
            "toca_para_agregar" to "Sakatu + gehitzeko",
            "puntuaciones_configuradas" to "posizio konfiguratuta",
            "sin_configurar" to "Konfiguratu gabe",
            "seleccionar_jugadores" to "Jokalariak aukeratu",
            "guardar" to "Gorde",
            "jugadores" to "Jokalariak",
            "puntuacion_por_posicion" to "Posizioaren puntuazioa",
            "configura_puntos" to "Konfiguratu posizio bakoitzean lortzen diren puntuak",
            "puntos" to "Puntuak:",
            "orden_invertido" to "Ordena alderantzikatua",
            "orden_invertido_desc" to "Gutxiago daukanak irabazten du",
            "guardar_puntuaciones" to "Puntuak gorde",
            "versiones" to "Bertsioak",
            "version_actual" to "Oraingo bertsioa",
            "creador" to "Sortzailea",
            "historial_versiones" to "Bertsioen historia",
            "volver" to "Itzuli",
            "cambiar_tema" to "Aldatu itxura",
            "historial" to "Historia",
            "anadir" to "Gehitu",
            "anade_jugadores" to "Gehitu jokalariak hasteko",
            "editar" to "Editatu",
            "eliminar_jugador" to "Ezabatu jokalaria",
            "confirmar_eliminar_jugador" to "Ezabatu?",
            "no_hay_ranking" to "Ez dago sailkapenik oraindik",
            "no_hay_partidas" to "Ez da partzik jokatu",
            "eliminar_partida" to "Ezabatu partida",
            "confirmar_eliminar_partida" to "Ezabatu partida hau?",
            "color" to "Kolorea",
            "nueva_partida_title" to "Partida Berria",
            "guardar_partida" to "Partida Gorde",
            "ok" to "OK",
            "posicion" to ".a",
            "clasificacion" to "Sailkapena"
        ),
        "es" to mapOf(
            "app_name" to "Partxis",
            "no_clasificaciones" to "No hay clasificaciones",
            "toca_para_crear" to "Toca + para crear una",
            "nueva_clasificacion" to "Nueva Clasificación",
            "nombre" to "Nombre",
            "crear" to "Crear",
            "cancelar" to "Cancelar",
            "eliminar" to "Eliminar",
            "eliminar_clasificacion" to "Eliminar clasificación",
            "confirmar_eliminar" to "Se borrarán todos los datos.",
            "creada" to "Creada",
            "partidas" to "Partidas",
            "ranking" to "Ranking",
            "configuracion" to "Configuración",
            "nueva_partida" to "Nueva partida",
            "sin_partidas" to "Sin partidas",
            "toca_para_agregar" to "Toca + para agregar una",
            "puntuaciones_configuradas" to "posiciones configuradas",
            "sin_configurar" to "Sin configurar",
            "seleccionar_jugadores" to "Seleccionar jugadores",
            "guardar" to "Guardar",
            "jugadores" to "Jugadores",
            "puntuacion_por_posicion" to "Puntuación por Posición",
            "configura_puntos" to "Configura los puntos que se ganan por cada posición",
            "puntos" to "Puntos:",
            "orden_invertido" to "Orden invertido",
            "orden_invertido_desc" to "Gana el que menos puntos tiene",
            "guardar_puntuaciones" to "Guardar Puntuaciones",
            "versiones" to "Versiones",
            "version_actual" to "Versión actual",
            "creador" to "Creador",
            "historial_versiones" to "Historial de versiones",
            "volver" to "Volver",
            "cambiar_tema" to "Cambiar tema",
            "historial" to "Historial",
            "anadir" to "Añadir",
            "anade_jugadores" to "Añade jugadores para empezar",
            "editar" to "Editar",
            "eliminar_jugador" to "Eliminar jugador",
            "confirmar_eliminar_jugador" to "Eliminar?",
            "no_hay_ranking" to "No hay ranking todavía",
            "no_hay_partidas" to "No hay partidas jugadas",
            "eliminar_partida" to "Eliminar partida",
            "confirmar_eliminar_partida" to "Eliminar esta partida?",
            "color" to "Color",
            "nueva_partida_title" to "Nueva Partida",
            "guardar_partida" to "Guardar Partida",
            "ok" to "OK",
            "posicion" to "º",
            "clasificacion" to "Clasificación"
        ),
        "en" to mapOf(
            "app_name" to "Partxis",
            "no_clasificaciones" to "No classifications",
            "toca_para_crear" to "Tap + to create one",
            "nueva_clasificacion" to "New Classification",
            "nombre" to "Name",
            "crear" to "Create",
            "cancelar" to "Cancel",
            "eliminar" to "Delete",
            "eliminar_clasificacion" to "Delete classification",
            "confirmar_eliminar" to "All data will be deleted.",
            "creada" to "Created",
            "partidas" to "Matches",
            "ranking" to "Ranking",
            "configuracion" to "Settings",
            "nueva_partida" to "New match",
            "sin_partidas" to "No matches",
            "toca_para_agregar" to "Tap + to add one",
            "puntuaciones_configuradas" to "positions configured",
            "sin_configurar" to "Not configured",
            "seleccionar_jugadores" to "Select players",
            "guardar" to "Save",
            "jugadores" to "Players",
            "puntuacion_por_posicion" to "Points by Position",
            "configura_puntos" to "Configure the points earned for each position",
            "puntos" to "Points:",
            "orden_invertido" to "Inverted order",
            "orden_invertido_desc" to "The one with fewer points wins",
            "guardar_puntuaciones" to "Save Points",
            "versiones" to "Versions",
            "version_actual" to "Current version",
            "creador" to "Creator",
            "historial_versiones" to "Version history",
            "volver" to "Back",
            "cambiar_tema" to "Toggle theme",
            "historial" to "History",
            "anadir" to "Add",
            "anade_jugadores" to "Add players to start",
            "editar" to "Edit",
            "eliminar_jugador" to "Remove player",
            "confirmar_eliminar_jugador" to "Remove?",
            "no_hay_ranking" to "No ranking yet",
            "no_hay_partidas" to "No matches played",
            "eliminar_partida" to "Remove match",
            "confirmar_eliminar_partida" to "Remove this match?",
            "color" to "Color",
            "nueva_partida_title" to "New Match",
            "guardar_partida" to "Save Match",
            "ok" to "OK",
            "posicion" to "º",
            "clasification" to "Classification"
        )
    )
}