package com.partxis.clasificacion.ui

object Strings {
    fun get(key: String, language: String): String {
        val translations = translationsMap[language] ?: translationsMap["eu"]!!
        return translations[key] ?: key
    }

    private val translationsMap = mapOf(
        "eu" to mapOf(
            "app_name" to "Partxis",
            "no_clasificaciones" to "Ez dago sailkapenik",
            "toca_para_crear" to "Sakatu + sortzeko",
            "nueva_clasificacion" to "Sailkapen berria",
            "nombre" to "Izena",
            "crear" to "Sortu",
            "cancelar" to "Utzi",
            "eliminar" to "Ezabatu",
            "eliminar_clasificacion" to "Sailkapena ezabatu",
            "confirmar_eliminar" to "Ziur zaude \"%1\$s\" ezabatu nahi duzula? Datu guztiak ezabatuko dira.",
            "creada" to "Sortuta: %1\$s",
            "partidas" to "Partidak",
            "ranking" to "Sailkapena",
            "configuracion" to "Konfigurazioa",
            "nueva_partida" to "Partida berria",
            "sin_partidas" to "Partida gabe",
            "toca_para_agregar" to "Sakatu + gehitzeko",
            "puntuaciones_configuradas" to "%1\$d posizio konfiguratuta",
            "sin_configurar" to "Konfiguratu gabe",
            "seleccionar_jugadores" to "Jokalariak aukeratu",
            "guardar" to "Gorde",
            "jugadores" to "Jokalariak",
            "puntuacion_por_posicion" to "Posizioaren puntuazioa",
            "configura_puntos" to "Konfiguratu posizio bakoitzean lortzen diren puntuak",
            "puntos" to "Puntuak:",
            "orden_invertido" to "Ordena alderantzikatua",
            "orden_invertido_desc" to "Gutxiago daukanak irabazten du",
            "guardar_puntuaciones" to "Puntuak gorde",
            "versiones" to "Bertsioak",
            "version_actual" to "Oraingo bertsioa",
            "creador" to "Sortzailea",
            "historial_versiones" to "Bertsioen historia",
            "volver" to "Itzuli",
            "cambiar_tema" to "Aldatu itxura"
        ),
        "es" to mapOf(
            "app_name" to "Partxis",
            "no_clasificaciones" to "No hay clasificaciones",
            "toca_para_crear" to "Toca + para crear una",
            "nueva_clasificacion" to "Nueva Clasificación",
            "nombre" to "Nombre",
            "crear" to "Crear",
            "cancelar" to "Cancelar",
            "eliminar" to "Eliminar",
            "eliminar_clasificacion" to "Eliminar clasificación",
            "confirmar_eliminar" to "¿Estás seguro de eliminar \"%1\$s\"? Se borrarán todos los datos.",
            "creada" to "Creada: %1\$s",
            "partidas" to "Partidas",
            "ranking" to "Ranking",
            "configuracion" to "Configuración",
            "nueva_partida" to "Nueva partida",
            "sin_partidas" to "Sin partidas",
            "toca_para_agregar" to "Toca + para agregar una",
            "puntuaciones_configuradas" to "%1\$d posiciones configuradas",
            "sin_configurar" to "Sin configurar",
            "seleccionar_jugadores" to "Seleccionar jugadores",
            "guardar" to "Guardar",
            "jugadores" to "Jugadores",
            "puntuacion_por_posicion" to "Puntuación por Posición",
            "configura_puntos" to "Configura los puntos que se ganan por cada posición",
            "puntos" to "Puntos:",
            "orden_invertido" to "Orden invertido",
            "orden_invertido_desc" to "Gana el que menos puntos tiene",
            "guardar_puntuaciones" to "Guardar Puntuaciones",
            "versiones" to "Versiones",
            "version_actual" to "Versión actual",
            "creador" to "Creador",
            "historial_versiones" to "Historial de versiones",
            "volver" to "Volver",
            "cambiar_tema" to "Cambiar tema"
        ),
        "en" to mapOf(
            "app_name" to "Partxis",
            "no_clasificaciones" to "No classifications",
            "toca_para_crear" to "Tap + to create one",
            "nueva_clasificacion" to "New Classification",
            "nombre" to "Name",
            "crear" to "Create",
            "cancelar" to "Cancel",
            "eliminar" to "Delete",
            "eliminar_clasificacion" to "Delete classification",
            "confirmar_eliminar" to "Are you sure you want to delete \"%1\$s\"? All data will be deleted.",
            "creada" to "Created: %1\$s",
            "partidas" to "Matches",
            "ranking" to "Ranking",
            "configuracion" to "Settings",
            "nueva_partida" to "New match",
            "sin_partidas" to "No matches",
            "toca_para_agregar" to "Tap + to add one",
            "puntuaciones_configuradas" to "%1\$d positions configured",
            "sin_configurar" to "Not configured",
            "seleccionar_jugadores" to "Select players",
            "guardar" to "Save",
            "jugadores" to "Players",
            "puntuacion_por_posicion" to "Points by Position",
            "configura_puntos" to "Configure the points earned for each position",
            "puntos" to "Points:",
            "orden_invertido" to "Inverted order",
            "orden_invertido_desc" to "The one with fewer points wins",
            "guardar_puntuaciones" to "Save Points",
            "versiones" to "Versions",
            "version_actual" to "Current version",
            "creador" to "Creator",
            "historial_versiones" to "Version history",
            "volver" to "Back",
            "cambiar_tema" to "Toggle theme"
        )
    )
}